### ISSUE TITLE
App gets stuck with the Initializing message on logging back in after logging out for the first time. 

### ISSUE THREAD

**Issue by anudr01d** [sightcall/Android-SDK-Helper#1]
Hey! First off, splendid job on the Helper app. 

While i was playing around with the app on different devices i came across an issue which i thought might be worth informing. Basically, I've been testing the RTCC-helper app on a Nexus 5 (which runs Android 5) and a Samsung Galaxy Tab2 (runs Android 4.1.2). 

Logging out and logging back in works fine on the Nexus 5, but on the Tab 2, if i try logging back in after i logout for the first time, the app gets stuck with the message "Initializing". 

I have attached the relevant logcat output to support the same.
http://goo.gl/P0W3Eu

**Comment by RomainGabriel** [comment]
Hi there,

I sincerely apologize for not replying sooner. This has been identified as a bug in our previous SDK version (5.3). 
Since we released the new SDK (5.4), this has been fixed.
However, this Helper application has not been upgraded, and it's still using the previous SDK version. 

So, basically, you won't experience this bug anymore developing your own application using the 5.4 SDK.

Regards.
